CREATE OR REPLACE
    TYPE PARTNER_NR_VAT AS VARRAY(10) OF VARCHAR2(50 CHAR);
/
CREATE OR REPLACE
    TYPE CHILD_NR_VAT AS VARRAY(10) OF NUMBER(38, 0);
/
CREATE OR REPLACE
    TYPE COLLECTIVE_CONTRACT_VAT AS VARRAY(2) OF NUMBER(38, 0);
/
CREATE
    TABLE ID_MAPPING(
        BEIHILFENR NUMBER NOT NULL
        ,PARTNER_NR VARCHAR2(50 CHAR) NOT NULL
        ,CONTRACT_NUMBER NUMBER(38, 0) NOT NULL
        ,PROCESS_NUMBER NUMBER(*, 0) NOT NULL
        ,MARRIAGE_PARTNER_NR VARCHAR2(50 CHAR)
        ,CHILDREN_PARTNER_NR PARTNER_NR_VAT
        ,CHILDREN_NR CHILD_NR_VAT
        ,COLLECTIVE_CONTRACT_NUMBERS COLLECTIVE_CONTRACT_VAT
        ,SCHULNUMMER VARCHAR2(6 byte)
        ,DIENSTSTELLE VARCHAR2(15 byte)
        ,MANDATOR NUMBER(*, 0) NOT NULL
        ,MIGRATION_USER VARCHAR2(50 CHAR) NOT NULL
        ,CONSTRAINT id_mapping_pk PRIMARY KEY (BEIHILFENR)
    );
CREATE
    PUBLIC SYNONYM ID_MAPPING FOR ID_MAPPING;
CREATE
    TABLE START_VALUES(
        MANDATOR NUMBER(*, 0) NOT NULL
        ,PARTNER_NUMBER NUMBER NOT NULL
        ,CONTRACT_NUMBER NUMBER NOT NULL
        ,PROCESS_NUMBER NUMBER NOT NULL
        ,COLLECTIVE_CONTRACT_NUMBER NUMBER NOT NULL
        ,CONSTRAINT start_values_pk PRIMARY KEY (MANDATOR)
    );
CREATE
    PUBLIC SYNONYM START_VALUES FOR START_VALUES;
    
