grant select, UPDATE,INSERT,DELETE ON MAPPING.ID_MAPPING TO beihilfe;
grant select ON MAPPING.START_VALUES TO beihilfe;

GRANT EXECUTE ON MAPPING.PARTNER_NR_VAT TO  beihilfe;
GRANT EXECUTE ON MAPPING.COLLECTIVE_CONTRACT_VAT TO  beihilfe;