
   CREATE TABLESPACE BEIHDAT 
   DATAFILE'tbs_beih_dat.dat'  SIZE 50M REUSE
   AUTOEXTEND ON NEXT 50M;
   
   
   CREATE TABLESPACE ADM_BEIHDAT 
   DATAFILE'tbs_adm_beih_dat.dat'  SIZE 50M REUSE
   AUTOEXTEND ON NEXT 50M;
  